version: '2'
services:
    appevent-app:
        image: appevent
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://appevent-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=appevent
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    appevent-mongodb:
        extends:
            file: mongodb.yml
            service: appevent-mongodb
